import { build } from 'vite';
// This deployment uses the persistent Express backend, not Firebase/static snapshots.
process.env.VITE_STATIC_SITE = 'false';
process.env.VITE_FIREBASE_SITE = 'false';
process.env.VITE_BASE_PATH = '/';
await build({
  build: { copyPublicDir: true },
  plugins: [{
    name: 'exclude-local-snapshots',
    async closeBundle() {
      const { rm } = await import('node:fs/promises');
      const { resolve, dirname, sep } = await import('node:path');
      const { fileURLToPath } = await import('node:url');
      const output = resolve(dirname(fileURLToPath(import.meta.url)), '../dist');
      // These are generated by other build modes and must not be published here.
      for (const folder of ['static-data', 'storage']) {
        const target = resolve(output, folder);
        if (!target.startsWith(output + sep)) throw new Error('Invalid output path');
        await rm(target, { recursive: true, force: true });
      }
    },
  }],
});
